# Generated by Django 3.2.4 on 2021-06-09 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_historicalhome_historicaluser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaluser',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.DeleteModel(
            name='HistoricalHome',
        ),
        migrations.DeleteModel(
            name='HistoricalUser',
        ),
    ]
