# Generated by Django 3.2.4 on 2021-06-10 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210609_2325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='booked_by',
        ),
        migrations.RemoveField(
            model_name='home',
            name='booking_status',
        ),
        migrations.CreateModel(
            name='BookingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('booked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.user')),
                ('house_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.home')),
            ],
        ),
    ]
